# Generated by Django 4.1.3 on 2022-12-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('website_link', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('no_of_employees', models.IntegerField()),
                ('no_of_students', models.IntegerField()),
                ('admin_email', models.CharField(max_length=100)),
                ('admin_role', models.CharField(max_length=50)),
                ('admin_sign', models.CharField(max_length=50)),
                ('date_of_sign', models.DateField()),
            ],
        ),
    ]
